title: My Github lab experience
author: GitHub User
email: someone@gmail.com
description: This part should contain meta info for the search engines...
  
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
